# Generated by Django 5.0.7 on 2024-07-13 18:01

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_user_managers_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created'], 'verbose_name': 'Комната', 'verbose_name_plural': 'Комнаты'},
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(help_text='Текст сообщения', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Время создания сообщения', verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.ForeignKey(help_text='Комната, в которой отправлено сообщение', on_delete=django.db.models.deletion.CASCADE, to='base.room', verbose_name='Комната'),
        ),
        migrations.AlterField(
            model_name='message',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Время последнего обновления сообщения', verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(help_text='Автор сообщения', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='room',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Время создания комнаты', verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, help_text='Введите описание комнаты', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='room',
            name='host',
            field=models.ForeignKey(help_text='Выберите хоста комнаты', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Хост'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(help_text='Введите название комнаты', max_length=200, verbose_name='Название комнаты'),
        ),
        migrations.AlterField(
            model_name='room',
            name='participants',
            field=models.ManyToManyField(blank=True, help_text='Выберите участников комнаты', related_name='participants', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='room',
            name='topic',
            field=models.ForeignKey(help_text='Выберите тему для комнаты', null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.topic', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='room',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Время последнего обновления', verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(help_text='Введите название темы', max_length=200, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar.svg', help_text='Загрузите аватар', null=True, upload_to='', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(help_text='Краткая информация о себе', null=True, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Введите ваш email', max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(help_text='Введите ваше имя', max_length=200, null=True, verbose_name='Имя'),
        ),
    ]
