# Generated by Django 5.0.7 on 2025-10-02 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_message_options_alter_room_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created'], 'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(help_text='Message text', verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Message creation time', verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.ForeignKey(help_text='Room where the message was sent', on_delete=django.db.models.deletion.CASCADE, to='base.room', verbose_name='Room'),
        ),
        migrations.AlterField(
            model_name='message',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Last update time', verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(help_text='Message author', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='room',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Room creation time', verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, help_text='Enter room description', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='room',
            name='host',
            field=models.ForeignKey(help_text='Select the room host', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Host'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(help_text='Enter the room name', max_length=200, verbose_name='Room name'),
        ),
        migrations.AlterField(
            model_name='room',
            name='participants',
            field=models.ManyToManyField(blank=True, help_text='Select room participants', related_name='participants', to=settings.AUTH_USER_MODEL, verbose_name='Participants'),
        ),
        migrations.AlterField(
            model_name='room',
            name='topic',
            field=models.ForeignKey(help_text='Select the topic for the room', null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.topic', verbose_name='Topic'),
        ),
        migrations.AlterField(
            model_name='room',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Last update time', verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(help_text='Enter topic name', max_length=200, verbose_name='Topic'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar.svg', help_text='Upload an avatar', null=True, upload_to='', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(help_text='Short information about yourself', null=True, verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Enter your email', max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(help_text='Enter your name', max_length=200, null=True, verbose_name='Name'),
        ),
    ]
